name: Parse and Update README
on:
  push:
    paths:
      - 'data/input.txt'
  workflow_dispatch:
    inputs:
      input_path:
        description: 'Path to input text file'
        default: 'data/input.txt'
        required: true

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install chardet

      - name: Read and normalize text
        id: parse
        shell: bash
        run: |
          FILE_PATH="${{ github.event.inputs.input_path || 'data/input.txt' }}"
          python3 - << 'EOF'
          import chardet, re
          raw_bytes = open(FILE_PATH, 'rb').read()
          detected = chardet.detect(raw_bytes)
          encoding = detected.get('encoding') or 'utf-8'
          raw = raw_bytes.decode(encoding, errors='ignore')
          cleaned = re.sub(r"[\x00-\x1F\x7F]+", '', raw)
          with open('README.md', 'w', encoding='utf-8') as out:
              out.write(cleaned)
          print(f'## Parsed Text (encoding: {encoding})')
          print(cleaned)
          EOF

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update README with parsed text (manual trigger support)'
          file_pattern: 'README.md'
          branch: ${{ github.ref_name }}
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
